### PR TITLE
fix: scroll error into view with nested key names

### PR DESCRIPTION
**Pull request by staffe**
Hello! I ran into an error when using nested fields with the option `scrollErrorIntoView: true`

The addon code evaluates to `document.querySelector('[name=fields.nestedfield]')` and throws the following exception:
`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'name=fields.nestedfield' is not a valid selector.`

The fix is to replace `.` with `\\.` in the query selector, i.e `document.querySelector('[name=fields\\.nestedfield]')`

Thank you!

### CODE REVIEW

**Comment by derrabauke** [comment]
Hey @staffe !

Thanks for pointing out this issue and for the provided fix. We will have a look at it as soon as possible.

Cheers

**Comment by derrabauke** [comment]
@staffe Could you please rebase onto `upstream/main` so the pipeline can run again and we can proceed with merging your PR.

**Comment by staffe** [comment]
> @staffe Could you please rebase onto `upstream/main` so the pipeline can run again and we can proceed with merging your PR.

Thanks, I've synced my fork

**Comment by derrabauke** [comment]
> > @staffe Could you please rebase onto `upstream/main` so the pipeline can run again and we can proceed with merging your PR.
> 
> Thanks, I've synced my fork

Glad for the quick response. It seems like you have to run `yarn lint:fix` und push again. ;)

**Comment by derrabauke** [comment]
> I see, sorry about that. It should be sorted now

No need to be sorry. Thanks for your contribution.

**Pull request merged**
